<a href="https://colab.research.google.com/github/selfmaded/python_study/blob/master/ML_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **로지스틱 회귀 알고리즘**

# 단일 입력 로지스틱 회귀 모델

**라이브러리 import**

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np

**로지스틱 회귀 모델 만들기**

In [ ]:
model = Sequential() # Sequential 모델을 model에 대입하여 선언
model.add(Dense(input_dim=1, units = 1)) # input_dim : 입력 뉴런 수, units : output 공간의 차원
model.add(Activation('sigmoid')) #사용할 활성화 함수
model.compile(loss='binary_crossentropy', #loss : cost function -> binary_crossentropy(카테고리가 2개인 경우)
              optimizer='sgd',            #optimizer : stochastic gradient descent (SGD)
              metrics=['binary_accuracy']) #binary_accuracy : 이진 분류의 정확도(출력이 0.5 이상일 경우 출력을 1로 판단, 출력이 0.5 이하일 경우 출력을 0으로 판단)

**데이터 생성**

In [ ]:
X = np.array([-2, -1.5, -1, 1.25, 1.62, 2]) # [-2, -1.5, -1, 1.25, 1.62, 2] numpy array를 X에 대입하여 선언
Y = np.array([0, 0, 0, 1, 1, 1]) # [0, 0, 0, 1, 1, 1] numpy array를 X에 대입하여 선언

**모델 학습 진행**

In [ ]:
model.fit(X, Y, epochs=300, verbose=0) # X, Y 데이터를 통해 model 학습, epoch: 에폭 수, verbose: 진행사항 시각화 모드 설정

**예측하기**

In [ ]:
model.predict([-2, -1.5, -1, 1.25, 1.62, 2]) # model을 통해 [-2, -1.5, -1, 1.25, 1.62, 2]에 대한 결과값 예측

array([[0.02704723],
       [0.0633273 ],
       [0.14120908],
       [0.89971095],
       [0.9454054 ],
       [0.97144955]], dtype=float32)

In [ ]:
model.predict([-1000, 1000]) # model을 통해 [-1000, 1000]에 대한 결과값 예측

array([[0.],
       [1.]], dtype=float32)

**모델 요약**

In [ ]:
model.summary() # model summary 내용 반환

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


**weight 확인**

In [ ]:
model.layers[0].get_weights() # model의 0번째 layer weight 값 반환

[array([[1.7774669]], dtype=float32), array([-0.02781698], dtype=float32)]

# 다중 입력 로지스틱 회귀 모델

**라이브러리 import**

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np

**로지스틱 회귀 모델 만들기**

In [ ]:
model = Sequential() # Sequential 모델을 model에 대입하여 선언
model.add(Dense(input_dim=2, units = 1)) # input_dim : 입력 뉴런 수, units : output 공간의 차원
model.add(Activation('sigmoid')) # model의 활성화 함수를 sigmoid로 설정
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['binary_accuracy']) # model compile, loss: 손실 함수 설정, optimizer: 최적화 함수 설정, metrics: 정확도 계산 방법 설정

**데이터 생성**

In [ ]:
X = np.array([(0,0), (0,1), (1,0), (1,1)])  # [(0,0), (0,1), (1,0), (1,1)] numpy array를 X에 대입하여 선언
Y = np.array([0, 0, 0, 1]) # [0, 0, 0, 1] numpy array를 에 대입하여 선언

**모델 학습 진행**

In [ ]:
model.fit(X, Y, epochs=5000, verbose=0) # X, Y 데이터로 model 학습, epoch: 에폭 수, verbose: 진행사항 시각화 모드 설정

**예측하기**

In [ ]:
model.predict(X) # model을 통해 X의 결과값 예측

array([[0.03593819],
       [0.22743897],
       [0.20943661],
       [0.67660236]], dtype=float32)

**모델 요약**

In [ ]:
model.summary() # model summary 내용 반환

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


**weight 확인**

In [ ]:
model.layers[0].get_weights() # model의 0번째 layer weight 값 반환

[array([[1.9610301],
        [2.0665257]], dtype=float32), array([-3.2893548], dtype=float32)]

# 소프트맥스 (다중 분류 로지스틱 회귀 모델)

**라이브러리 import**

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist

**데이터셋 수집 및 탐색**

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data() # mnist 데이터를 로드하여 학습데이터(X,y), 평가데이터(X,y)를 각각 X_train, y_train, X_test, y_test에 대입하여 선언
print("train data (count, row, column) : " + str(X_train.shape) ) # X_Train 데이터의 shape을 string형태로 변환하여 출력
print("test data  (count, row, column) : " + str(X_test.shape) ) # X_test 데이터의 shape을 string형태로 변환하여 출력

11493376/11490434 [==============================] - 0s 0us/step
train data (count, row, column) : (60000, 28, 28)
test data  (count, row, column) : (10000, 28, 28)


In [ ]:
print(X_train[0]) #학습 데이터 1개를 출력

**데이터 정규화**

In [ ]:
X_train = X_train.astype('float32')  # X_train 데이터를 float32형태로 변환
X_test = X_test.astype('float32')  # X_test 데이터를 float32형태로 변환
X_train /= 255 # X_train 전체 데이터를 255로 나눔
X_test /= 255 # X_test 전체 데이터를 255로 나눔

print(X_train[0]) #학습 데이터 1개를 출력

In [ ]:
print("train target (count) : " + str(y_train.shape) )  # y_train 데이터의 shape을 string형태로 변환하여 출력
print("test target  (count) : " + str(y_test.shape) ) # y_test 데이터의 shape을 string형태로 변환하여 출력

train target (count) : (60000,)
test target  (count) : (10000,)


In [ ]:
print("sample from train : " + str(y_train[0]) ) # y_train에서 0번째 데이터를 string 형태로 변환하여 출력
print("sample from test : " + str(y_test[0]) ) # y_test에서 0번째 데이터를 string 형태로 변환하여 출력

sample from train : 5
sample from test : 7


**데이터 단순화**

In [ ]:
input_dim = 784 # 28*28 
X_train = X_train.reshape(60000, input_dim) # x_train 데이터를 [28, 28] 2차원 행렬에서 [784] 1차원 행렬로 reshape
X_test = X_test.reshape(10000, input_dim) # x_test 데이터를 [28, 28] 2차원 행렬에서 [784] 1차원 행렬로 reshape
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


**소프트맥스**

In [ ]:
num_classes = 10
y_train = to_categorical(y_train, num_classes) # y_train데이터를 10(num_classes)개의 클래스를 갖는 categorical 데이터로 변환
y_test = to_categorical(y_test, num_classes) # y_test데이터를 10(num_classes)개의 클래스를 갖는 categorical 데이터로 변환
print(y_train[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


**모델 학습**

In [ ]:
model = Sequential()  # Sequential 모델을 model에 대입하여 선언
model.add(Dense(input_dim=input_dim, units = 10, activation='softmax')) # input layer 선언, input_dim : 입력 뉴런 수, units : output 공간의 차원, activation: 활성화 함수 설정
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy']) # model compile, loss: 손실 함수 설정, optimizer: 최적화 함수 설정, metrics: 정확도 계산 방법 설정
model.fit(X_train, y_train, batch_size=2048, epochs=100, verbose=0) # X_train, y_train 데이터를 통해 model 학습, batch_size: 배치 크기 설정, epoch: 에폭 수, verbose: 진행사항 시각화 모드 설정

**모델 테스트**

In [ ]:
score = model.evaluate(X_test, y_test)  # X_test, y_test 값을 통해 model 정확도를 계산한 후 score에 대입하여 선언
print('Test accuracy:', score[1])

313/313 [==============================] - 1s 2ms/step - loss: 0.4225 - accuracy: 0.8893
Test accuracy: 0.8892999887466431


**모델 요약**

In [ ]:
model.summary() # model summary 내용 반환

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.layers[0].get_weights() # model의 0번째 layer weight 값 반환 

[array([[ 0.06003564,  0.01880657, -0.0500227 , ..., -0.03777415,
         -0.06845812, -0.02365827],
        [ 0.03003573, -0.01267216,  0.04849791, ..., -0.03808445,
         -0.08689357, -0.02334825],
        [-0.01617073, -0.00285913, -0.08234502, ...,  0.07006595,
          0.07877513,  0.04902393],
        ...,
        [-0.01080633,  0.07791851, -0.01975209, ..., -0.03589239,
         -0.0413778 ,  0.02030614],
        [-0.05988739,  0.07429858,  0.01257917, ...,  0.04241062,
          0.00589474, -0.0400427 ],
        [ 0.0680731 ,  0.07623536, -0.00642883, ...,  0.04020619,
         -0.0095406 , -0.04738884]], dtype=float32),
 array([-0.08497713,  0.16926983, -0.02705523, -0.04466618,  0.04624446,
         0.16056952, -0.02151994,  0.09545762, -0.24948536, -0.04383735],
       dtype=float32)]